2020-04-15 20:12:14,470 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 11:36:59,517 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 11:37:06,232 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 11:37:24,192 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 13:52:24,389 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 14:20:00,322 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 14:21:56,133 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 14:32:03,561 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 14:34:13,851 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 14:41:46,134 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 15:07:34,747 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 16:01:03,080 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 16:23:24,421 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 16:34:19,931 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 16:35:17,242 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:43]
2020-04-16 18:31:49,605 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:45]
2020-04-16 18:32:20,734 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:45]
2020-04-16 18:38:49,774 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:45]
2020-04-16 20:30:33,149 INFO: Microblog startup [in C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\__init__.py:45]
2020-04-16 20:31:26,623 ERROR: Exception on /reset_password_request [POST] [in c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials x18sm5415878wmi.29 - gsmtp')
2020-04-16 20:31:27,691 ERROR: Exception on /reset_password_request [POST] [in c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\routes.py", line 161, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\email.py", line 13, in send_password_reset_email
    send_email('[Microblog] Reset Your Password',
  File "C:\Users\Ling Sang 2\Documents\Git Bash\microblog\app\email.py", line 9, in send_email
    mail.send(msg)
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 491, in send
    with self.connect() as connection:
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 144, in __enter__
    self.host = self.configure_host()
  File "c:\users\ling sang 2\documents\git bash\microblog\venv\lib\site-packages\flask_mail.py", line 165, in configure_host
    host.login(self.mail.username, self.mail.password)
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 734, in login
    raise last_exception
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "C:\Users\Ling Sang 2\AppData\Local\Programs\Python\Python38-32\lib\smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials b85sm5717468wmb.21 - gsmtp')
